backend:
  name: github
  repo: Dirout/stanton
  branch: master
  open_authoring: true
publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
site_url: https://dirout.github.io/stanton
logo_url: https://dirout.github.io/assets/icons/vector/logo.svg
collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "articles/{{slug}}.html"
    extension: "mokkf"
    format: "yaml-frontmatter"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "articles"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/{{ page.data.collection }}/{{ page.name }}.html"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", format: "YYYY-MM-DDTHH:mm:ss+00:00"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Markdown", name: "markdown", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
